### PR TITLE
Fix(gqlgen): Different alias with same name in inline fragment

### LINKED ISSUE #1299: Same field with alias in a fragment is getting ignored in collectFields
### What happened?
For this query:
```
query {
  queryCharacter {
    ... on Human {
      name
      n: name
    }
  }
}
```
The selection set returned by `collectFields` contains only the field `name`. It doesn't contain the aliased field `n: name`.

### What did you expect?
I expect the selection set returned by `collectFields` to contain both `name` and the aliased field `n: name`.

### Minimal graphql.schema and models to reproduce
```
interface Character {
        id: ID!
        name: String!
}

type Human implements Character {
        totalCredits: Float
}
```

### versions
 - `gqlgen version`? v0.12.2
 - `go version`? go1.14 linux/amd64
 - dep or go modules? go modules

### PR DESCRIPTION
**Pull request by vmrajas**
Fixes https://github.com/99designs/gqlgen/issues/1299

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))

### CODE REVIEW

File: graphql/context_operation_test.go [hunk 1]
```diff
@@ -106,4 +106,31 @@ func TestCollectAllFields(t *testing.T) {
...
+						Alias:            "fieldA",
+						ObjectDefinition: &ast.Definition{Name: "ExampleTypeA"},
+					},
+					&ast.Field{
+						Name:             "fieldA",
+						Alias:            "fieldA Alias",
+						ObjectDefinition: &ast.Definition{Name: "ExampleTypeA"},
+					},
+				},
+				ObjectDefinition: &ast.Definition{Name: "Interface"},
```
Comment (abhimanyusinghgaur) [inline graphql/context_operation_test.go]:
```suggestion
				ObjectDefinition: &ast.Definition{Name: "ExampleType", Kind: ast.Interface},
```
Can we name it something else? `Interface` name can confuse people with `interface` kind, lets name it `ExampleType` or something else.

**Review by abhimanyusinghgaur — APPROVED** [review]
Just one minor comment. Otherwise, Looks good.

File: graphql/context_operation_test.go (hunk 1 above)
Comment (vmrajas) [reply graphql/context_operation_test.go]: Renamed to ExampleType.
